/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddTodo: typeof import('./src/components/todo/AddTodo.vue')['default']
    EditTodo: typeof import('./src/components/todo/EditTodo.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    FetchTodos: typeof import('./src/components/todo/FetchTodos.vue')['default']
    LeftSide: typeof import('./src/components/LeftSide.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    RightSide: typeof import('./src/components/RightSide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoDetail: typeof import('./src/components/todo/TodoDetail.vue')['default']
    UserCenter: typeof import('./src/components/user/UserCenter.vue')['default']
    UserLogin: typeof import('./src/components/user/UserLogin.vue')['default']
    UserRegister: typeof import('./src/components/user/UserRegister.vue')['default']
  }
}
